# Generated by Django 2.2 on 2019-08-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefreeitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefreeitem',
            old_name='created_on',
            new_name='create_on',
        ),
    ]
