# Generated by Django 2.2 on 2019-08-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20190810_2228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFreeItem',
            new_name='ProfileFeedItem',
        ),
    ]
